name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }
      - run: npm ci || npm i
      - run: npm run build --if-present
      - name: Smoke quick_check
        env:
          PUBLIC_BASE_URL: ${{ secrets.PUBLIC_BASE_URL }}
          HEALTH_CHECK_TOKEN: ${{ secrets.HEALTH_CHECK_TOKEN }}
        run: |
          if [ -z "$PUBLIC_BASE_URL" ]; then
            echo "PUBLIC_BASE_URL manquant (Secrets GitHub). On skip le smoke test."
            exit 0
          fi
          if [ ! -f quick_check.sh ]; then
            cat > quick_check.sh << 'EOSH'
            #!/usr/bin/env bash
            set -e
            BASE="${1:-http://localhost:3000}"
            echo "# /api/products"; curl -s "$BASE/api/products" | head -c 200 || true; echo
            echo "# /api/customs/estimate"; curl -s -X POST "$BASE/api/customs/estimate" -H 'Content-Type: application/json' -d '{"island":"MQ","family":"high-tech","cif":100,"duty_rate":0.0}' || true; echo
            echo "# /api/sys/returns/health"; curl -s -H "X-Health-Check: ${HEALTH_CHECK_TOKEN:-test}" "$BASE/api/sys/returns/health" || true; echo
            EOSH
            chmod +x quick_check.sh
          fi
          bash quick_check.sh "$PUBLIC_BASE_URL" || true